name: brokerapp

services:

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - nodereddata:/data
    networks:
      backend:
        ipv4_address: 172.20.0.2

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquittoconfig:/mosquitto/config
      - mosquittodata:/mosquitto/data
      - mosquittolog:/mosquitto/log
    networks:
      backend:
        ipv4_address: 172.20.0.3

volumes:
  nodereddata:
  mosquittoconfig:
  mosquittodata:
  mosquittolog:

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16